### ISSUE TITLE
After update to 3.0.2 bfs no longer builds with same Makefile on FreeBSD

### ISSUE THREAD

**Issue by driesmp** [tavianator/bfs#125]
Hello, when I try to update to 3.0.2 the port fails to build with the error below. This is not present on 3.0.1, you know which might be the cause?

===>  Configuring for bfs-3.0.2
===>  Building for bfs-3.0.2
gmake[2]: Entering directory '/usr/ports/sysutils/bfs/work/bfs-3.0.2'
gmake[2]: Makefile: No such file or directory
**gmake[2]: *** No rule to make target 'Makefile'.  Stop.**
gmake[2]: Leaving directory '/usr/ports/sysutils/bfs/work/bfs-3.0.2'
===> Compilation failed unexpectedly.

**Comment by tavianator** [comment]
I assume the culprit is https://github.com/tavianator/bfs/commit/44cf900b78f7a9e6a838c82be38ddad3c0c60a25

**Comment by driesmp** [comment]
Ok derp, easy fix, https://cgit.freebsd.org/ports/commit/?id=d7ba45f6bcbc046d9ca6b670cab78b9a458d90bf, closing this.
